apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: restaurant
          image: ogioldat/restaurant:0.6.0
          command: ["/"]
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: restaurant
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restaurant
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: restaurant
                port:
                  number: 80
