spin_manifest_version = 2

[application]
name = "restaurant"
version = "0.9.0"
authors = ["ogioldat <tomasz.ogiolda00@gmail.com>"]
description = "Accepting and serving orders"

[[trigger.http]]
route = "/"
component = "restaurant"

[component.restaurant]
source = "target/wasm32-wasi/release/restaurant.wasm"
allowed_outbound_hosts = []
[component.restaurant.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/menu"
component = "menu-api"

[component.menu-api]
source = "menu-api/target/wasm32-wasi/release/menu_api.wasm"
allowed_outbound_hosts = []
[component.menu-api.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "menu-api"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/kitchen"
component = "kitchen-api"

[component.kitchen-api]
source = "kitchen-api/target/wasm32-wasi/release/kitchen_api.wasm"
allowed_outbound_hosts = []
[component.kitchen-api.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "kitchen-api"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/order"
component = "order-api"

[component.order-api]
source = "order-api/target/wasm32-wasi/release/order_api.wasm"
environment = { REDIS_ADDRESS = "redis.default.svc.cluster.local" }
allowed_outbound_hosts = []
[component.order-api.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "order-api"
watch = ["src/**/*.rs", "Cargo.toml"]
