apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kitchen
  template:
    metadata:
      labels:
        app: kitchen
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: kitchen
          image: ogioldat/kitchen:0.7.0
          command: ["/"]
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: kitchen
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: kitchen
