spin_manifest_version = 2

[application]
name = "kitchen"
version = "0.1.0"
authors = ["ogioldat <tomasz.ogiolda00@gmail.com>"]
description = "Preparing orders"

[application.trigger.redis]
address = "redis://redis.default.svc.cluster.local:6379"

[[trigger.redis]]
channel = "restaurant" # the channel that the trigger subscribes to
component = "kitchen"

[component.kitchen]
source = "target/wasm32-wasi/release/kitchen.wasm"
[component.kitchen.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
