spin_manifest_version = 2

[application]
name = "kitchen"
version = "0.8.0"
authors = ["ogioldat <tomasz.ogiolda00@gmail.com>"]
description = "Preparing orders"

[application.trigger.redis]
address = "redis://redis.default.svc.cluster.local:6379"

[[trigger.redis]]
channel = "restaurant"
component = "kitchen"

[component.kitchen]
source = "target/wasm32-wasi/release/kitchen.wasm"
environment = { REDIS_ADDRESS = "redis://redis.default.svc.cluster.local:6379", REDIS_CHANNEL = "restaurant" }
allowed_outbound_hosts = ["redis://redis.default.svc.cluster.local:6379"]
[component.kitchen.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
