apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: jaeger-n-fun
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
        app: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: docker.io/ogioldat/nodejs:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service  
  namespace: jaeger-n-fun
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: py
  namespace: jaeger-n-fun
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
        app: py
  replicas: 1
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: py
        image: docker.io/ogioldat/py:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: py-service
  namespace: jaeger-n-fun  
spec:
  type: LoadBalancer
  selector:
    app: py
  ports:
    - port: 8080
      targetPort: 8080
