apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: restaurant
          image: ogioldat/restaurant:0.20.0
          command: ["/"]
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: restaurant
