apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  namespace: wasi-wasm-docker
spec:
  selector:
    matchLabels:
        app: core-api
  replicas: 1
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
      - name: nodejs
        image: docker.io/ogioldat/core-api-wasm:latest
        imagePullPolicy: Always

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime
  namespace: wasi-wasm-docker
handler: wasmtime
scheduling:
  nodeSelector:
    wasmtime-enabled: "yes"
handler: "wasmtime"